### ISSUE TITLE
Scrap Reduction Reset Upon Loading Saved Game

### ISSUE THREAD

**Issue by thundershocker1** [JackEhttack/DiminishingReturns#11]
For some reason, the scrap reduction amounts aren't saved, so when you reload the game, all the moons with reduced scrap no longer have reduced scrap. Furthermore, could you eventually introduce an option in the Config Editor that allows for all moons to fully refill scrap-wise upon getting a new quota, as well as an option to make the moon have reduced scrap equal to the amount of scrap retrieved?

**Comment by thundershocker1** [comment]
Furthermore, could you eventually introduce an option in the Config Editor that allows for all moons to fully refill scrap-wise upon getting a new quota?

**Comment by thundershocker1** [comment]
Just sending a followup message in case you haven't seen the original message. Please reply if you've seen it.

**Comment by JackEhttack** [comment]
> Just sending a followup message in case you haven't seen the original message. Please reply if you've seen it.

Looking into now.

> option [...] that allows for all moons to fully refill scrap-wise upon getting a new quota

This is planned.

> option to make the moon have reduced scrap equal to the amount of scrap retrieved?

This aswell.
Both will come out in the next major update when I get time.

**Comment by JackEhttack** [comment]
I recently added a config option that allowed for moons to diminish by a lesser amount than full, and in doing so I swapped the value that kept track of diminishment from an int to a float. And I clearly forgot to fix the save/load code to account for this.
`
var values = ES3.Load<int[]>("MoonTrackerValues", currentSaveFileName, []).ToList();
`
vs.
`
var values = ES3.Load<float[]>("MoonTrackerValues", currentSaveFileName, []).ToList();
`
The nice thing about this bug is that the saved data is still there and has been saved properly, so when you update the mod you'll be able to load the old save. I'll release this patch very shortly from now and start work on the next proper update.
