### ISSUE TITLE
(Suggestion) Every Scrap that goes, stays gone

### ISSUE THREAD

**Issue by VanilaBOI** [JackEhttack/DiminishingReturns#3]
While I'm not sure if I under stand this mod correctly.
Because when I use general improvements to show me the amount of Scrap is on a moon, I haven't noticed a decrease of Scrap even though it should be 35% less according to the TRACKER.

But what I'd really love to see is that the amount of loot which you take home from a moon would stay gone until you finish a qouta.

Ex.: There are 10 Scrap Items on Experimentation and you bring back 8 which results in Experimentation to only offer 20% of the scrap amount till the next quota rolls around.
You could also have an amount of % to regenerate each day.

**Comment by JackEhttack** [comment]
> Because when I use general improvements to show me the amount of Scrap is on a moon, I haven't noticed a decrease of Scrap even though it should be 35% less according to the TRACKER.

The amount of scrap of any particular moon varies by a bit. On Experimentation you could get 9 scrap with 0% diminishment and when you go the next day get 13 scrap with 33% diminishment which still leaves you with 9 scrap. If you want to confirm the functionality of the mod crank the max diminishment up to 0.99 and see how much scrap is left.

As for your other request... I'm shooting myself in the foot here by saying this but:
https://thunderstore.io/c/lethal-company/p/coookies369/DeminishingReturns/

This mod tracks the number of items you collect and diminishes the moon accordingly. It also allows you to regenerate the moons during quota rollover instead of slowly or even increase by a certain percent a day.

**Comment by JackEhttack** [comment]
I just realized that that other mod no longer works as of the new version but I'm not going to add scrap counting to this mod, or quota diminish reset either.
The entire point of this mod is to encourage the crew to visit a variety of moons.

These features do not fit the point of this mod because:
1. If it resets every quota then there is less incentive to visit new moons because the old ones will have regenerated.
2. A flat penalty to the amount of scrap on a moon is more desirable to me than a scaling penalty. It encourages you to grab as much scrap as possible in the first run and incentivize you to move onto a new moon. With the scaling penalty if you do poorly on a scrap run and bring little to nothing back you are encouraged to stay on the current moon especially if it's a paid moon.

**Comment by VanilaBOI** [comment]
For the top comment I have to agree that there is the possibility of there being a range that looks like it didn't change anything because you got a high scrap count but that's why I simply do exp because it can only have 8 - 12 Scrap.
So if I get 7 there, it definitely worked and when I have 11 it definitively didn't.(p.s. I first did 0.2 but since it regenerated at least 1 stage before you can even land, before your fix, I ended up with 0.4 which led to some confusion but I figured it out in the end)
That's why I set it to 0.99 after a while and finally figured out what the Tracker is actually telling me:
(config: diminish=0.9/days to regen=4) I went down on a moon EXP = 10%, came back up and the tracker said EXP = 32.5%
My Brain: How is it only diminished by 32.5%(I thought it meant diminished by and not diminished down to)

I do have to say that I 100% have noticed your mod not working once when I did a test on march and since I had the numbers of how many items could spawn there(because I see it with advanced company) I went on it twice and the amount of scrap went up instead of down and even with accounting for the 1 day of regenerating, it still should have only given me max 40 % and it was way above that.
But it doesn't matter because since you fixed the softlock bug it will be a lot more enjoyable to test/play :)

**Comment by VanilaBOI** [comment]
And on your second Comment I have to admit I was just hoping this mod could replace the other diminishing Returns mod because I'm doing a mod pack where I use Lethal Constellations and I had it set up so you have to pay for basically any moon because the moons themselves don't cost anything to travel to only the Constantions which always have 3 different looking moons(ex. Adamance/Offence/Dine) so it encourages going to a different looking/value moon each quota, keeping the game feeling less repetitive and midmaxy.

Now I could argue that even in a vanilla setting, having the exact amount of scrap taken be decreased, makes it more personal having actually "sucked the moon dry" instead of "Oh you went on Titan and got locked out by a jester and tricky placed traps, whelp sucks to be you, go find a new moon".
I think it's more intuitive to have the amount matter since thats the point of going to any moon anyway(and is actually controlled by the player and not RNG) and maybe have a setting that lets you buffer how many days it takes of you not going on that moon for it to "heal".

But hey it's your mod, you make it fill the roll you want filled. I'm just honestly soooo glad you actually update your mod
Thank you so much for that!!

**Comment by JackEhttack** [comment]
I've thought about it a bit, and I think I'll add scrap counting as a non-default config option, and quota reset I suppose. They are trivially easy to implement (ctrl+c & ctrl-v code from the other mod, thank you MIT License lol). I'll work on this sometime in the near future.
